#!/bin/sh
set -e

config=/etc/intelmq/contactdb-serve.conf

if [ "$1" = "configure" ] ; then
    if [ ! -e $config ] ; then
        python3 -m contactdb_api --example-conf >$config
    fi

    if ! getent passwd www-fody >/dev/null 2>&1; then
        useradd --system -s /usr/sbin/nologin -d /tmp www-fody
    fi

    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke enmod proxy
    apache2_invoke enmod rewrite
    apache2_invoke ensite 001-fody.conf
fi

#DEBHELPER#

