name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Ubuntu 20.04, 22.04, 24.04. Not compatible with 3.13.
        # 3.12 fails because of missing package 'distutils'
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Build package
        run: |
          pip install .
          pip install ./checkticket_api ./contactdb_api ./events_api ./session ./tickets_api
      - name: Test with pytest
        run: pytest
        env:
          PYTHONPATH: .
